StartupEvents.registry('item', event => {
  event.create('blank_music_disc')
    .displayName('Blank Music Disc')
    .maxStackSize(16)
  event.create('empty_ink_sac')
    .displayName('Empty Ink Sac')
  event.create('incomplete_enchanted_golden_apple')
    .displayName('Incomplete Echanted Golden Apple')
    .maxStackSize(1)
    .texture('minecraft:item/golden_apple')
  event.create('incomplete_netherite_scrap')
    .displayName('Incomplete Netherite Scrap')
})

StartupEvents.registry('block', event => {
  event.create('concrete_powder', 'falling')
    .displayName('Concrete Powder')
    .fullBlock(true)
    .sandSoundType()
    .hardness(0.5)
    .mapColor('terracotta_white')
    .requiresTool(false)
    .resistance(0.5)
    .tagBlock('malalib:concrete_powder_fix')
    .tagBlock('malalib:gravity_blocks')
    .tagBlock('minecraft:camel_sand_step_sound_blocks')
    .tagBlock('minecraft:concrete_powder')
    .tagBlock('minecraft:mineable/shovel')
    .tagItem('c:concrete_powders')
})